# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c692908809081d56aced93f2b6faa5f621185347a7dad55fa0951bbd2125c0fa22b780d0b29cf1ca2d933017a2d34ae1f01cf71ac7e5948eac48d987ba74d2fd

test:
  secret_key_base: a6590eeafce89dcb721a12bb4351ddf92e2caeadf36a74a868a9e0a14b58c8c670ee0ad1f7621ceafe8e8ba4aa020388d7ae5047556899706fa4ed9a70a33208

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
